spring:
  application:
    name: habit-tracker

  datasource:
    url: jdbc:postgresql://dpg-d2ebt50dl3ps73a41brg-a.oregon-postgres.render.com/habit_db_gsl4
    username: tyro
    password: xgWa9hpPIwNBGs4zVy9sbLaovxOUTCNx
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 465
    username: mikedetyro1@gmail.com
    password: uwnlzuybklozmrkr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.gmail.com

jwt:
  secret: 9F8B67A143C1D2937D8E5609EA1F9C435F31A26DC57DCA35B1A84EF2E8A34FC51979C43CEB5E867AC1B4A329E3F0B973AA8A6E8D8F4DE31E3E446F3029386A37
  expiration: 86400000

server:
  port: ${PORT:8080}

app:
  base-url: http://localhost:8080
