spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/habit_tracker}
    username: ${MYSQLUSER:${DB_USERNAME:root}}
    password: ${MYSQLPASSWORD:${DB_PASSWORD:password}}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

jwt:
  secret: ${JWT_SECRET:dev-secret}
  expiration: ${JWT_EXPIRATION:86400000}
