version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: habit_mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: habit_tracker
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  habit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habit_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  mysql_data:
